stName = input("enter the student name")
stUSN =input("enter the student USN")
stMarks1 = int(input("student marks1"))
stMarks2 = int(input("student marks2"))
stMarks3 = int(input("student marks3"))
print("student details\n___________________")
print("Name:",stName) 
print("USN:",stUSN) 
print("Marks 1:",stMarks1) 
print("Marks 2:",stMarks2) 
print("Marks 3:",stMarks3) 
print("Total:",stMarks1+stMarks2+stMarks3) 
print("Percentage:","%2f"%((stMarks1+stMarks2+stMarks3)/3)) 
print("-------------------------------------------------------")
